### ISSUE TITLE
ZM_TMPDIR directive doesn't appear to work

### ISSUE THREAD

**Issue by PX03AFK** [ZoneMinder/ZoneMinder#306] opened 2014-01-24 08:05 UTC
When compiling ZM 1.26.5, because of an issue with systemd using private /tmp directories, I wanted to get ZM to use a different directory for temporary files.  However when a version recompiled using -D ZM_TMPDIR=/var/run/zmtmp directive appeared to create the specified directory but continued to use /tmp for temporary space.

**Comment by knnniggett** [comment] 2015-08-15 13:56
From memory, I believe the root cause of this issue was due to newer distros moving to private tmpfs folders.  We have since changed the defaults in zoneminder to work around this, which should mean this can be closed.

@PX03AFK Let me know if I am mistaken.

**Closed by knnniggett** 2015-08-15 13:56 UTC
