### ISSUE TITLE
Error by adding Groups

### ISSUE THREAD

**Issue by bartbk** [ZoneMinder/zoneminder#2939] opened 2020-05-22 19:18 UTC
**Describe Your Environment**
- Version of ZoneMinder [1.34.15]
- How you installed ZoneMinder [e.g. PPA iconnor]
- Full name and version of OS Ubuntu 20.04
- Browser name and version (Chrome Version 81.0.4044.138 (Official Build) (64-bit) / Edge Version 84.0.516.0 (Official build) canary (64-bit) )

**If the issue concerns a camera**
- Make and Model
- frame rate
- resolution
- ZoneMinder Source Type:

**Describe the bug** 
Every time I try to add group
SQL-ERR 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Groups (`Id`, `Name`, `ParentId`) VALUES (?, ?, ?)' at line 1', statement was 'INSERT INTO Groups (`Id`, `Name`, `ParentId`) VALUES (?, ?, ?)' params:,Podjazd,
**To Reproduce**
1. Go to Zonemider Web
2. Click on Groups
3. Click New 
4. Enter any name, Parent group = None, Monitor = Select Monitor 1 / Leave as is
3. Click Save
4. See error in log

**Expected behavior**
Add a group with name selected.

**Debug Logs**
SQL-ERR 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Groups (`Id`, `Name`, `ParentId`) VALUES (?, ?, ?)' at line 1', statement was 'INSERT INTO Groups (`Id`, `Name`, `ParentId`) VALUES (?, ?, ?)' params:,Podjazd,

```

**Comment by connortechnology** [comment] 2020-06-11 22:52
I believe these issues were fixed in 1.34.16.  Please update and close this issue if the problem is sovled.

**Closed** 2020-06-15 19:35 UTC
