### ISSUE TITLE
Recording more than 1 hour with MODECT

### ISSUE THREAD

**Issue by juanmoura** [ZoneMinder/zoneminder#2139] opened 2018-07-02 19:57 UTC
I'm using all the monitors with MODECT and I left well regulated to record only the movement, the problem is that in fact there is constant movement. I've already changed EVENT_CLOSE_MODE to time, but it does not stop, it continues to save.
I'm looking for a way to split the files, so the event face has at most the amount that I inserted in Section length.

https://i.imgur.com/Ya8emEY.png

**Comment by knight-of-ni** [comment] 2018-07-02 20:23
Closing, as this is not a bug report and is a double post.
Feel free to continue your discussion in the user forum:
https://forums.zoneminder.com/viewtopic.php?f=37&t=27354

**Closed by knight-of-ni** 2018-07-02 20:23 UTC
