### ISSUE TITLE
HTTP API does not work

### ISSUE THREAD

**Issue by Veles** [ZoneMinder/zoneminder#1985] opened 2017-09-19 09:39 UTC
Hello. In my instance of zm http api does not work.
I use this manual https://zoneminder.readthedocs.io/en/stable/api.html
I trued this without  authorization:
```
$ curl http://localhost:81/api/monitors.json
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/monitors.json was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at localhost Port 81</address>
</body></html>
```
My version is 
```
zmaudit.pl -v
1.31.1
```

running inside docker container from ppa:iconnor/zoneminder-master

When i open http://localhost:81/api/ in browser i receive 
```
CakePHP: the rapid development php framework

Not Found

Error: The requested address '/api/' was not found on this server.

CakePHP: the rapid development php framework
CakePHP 2.8.0
``` 

How i can fix it?

**Comment by mnoorenberghe** [comment] 2017-09-21 07:21
Probably a dupe of #1962

**Comment by knnniggett** [comment] 2018-01-14 21:01
We've made a few changes and moved our dockerfiles to a new home:
https://github.com/ZoneMinder/zmdockerfiles

Try that one.

**Closed by knnniggett** 2018-01-14 21:01 UTC
