### ISSUE TITLE
Events are randomly recorded in the wrong folder on filesystem 

### ISSUE THREAD

**Issue by marcschh** [ZoneMinder/zoneminder#2755] opened 2019-11-20 11:47 UTC
- zoneminder 1.32.3-bionic
- PPA: http://ppa.launchpad.net/iconnor/zoneminder-1.32/ubuntu bionic main
- Ubuntu 18.04.3
- Firefox 70 / Chromium 77

**Describe the bug**
Last time (around Mid of November 2019) zoneminder sometimes record events with end time much more then expected from duration. Those events doesn't have an thumbnail and they are not replayed.
Somehow on the filesystem those events seems to be in the wrong folder.
Based on the screenshot https://pasteboard.co/IHyrthT.png
Event 6033:

6033 | Event- 6033 | Garage | Motion                    Motion: fernbereich | 
11/19 14:34:29 until 11/19 01:59:22 | 00:00:32 | 229 | 6 | 23 | 3 | 10 | 

Event 6036:
6036 | Event- 6036 | GarageTor1024 | Motion                    Motion: Neu | 
11/19 14:35:49 until 11/19 02:03:45 | 00:00:23 | 164 | 4 | 13 | 3 | 4 | 

$ ls -ltr /data/Garage/2019-11-19/
drwxr-xr-x 2 www-data www-data 74 Nov 19 12:11 5987
drwxr-xr-x 2 www-data www-data 48 Nov 19 12:11 5990
drwxr-xr-x 2 www-data www-data 48 Nov 19 12:26 5993
drwxr-xr-x 2 www-data www-data 48 Nov 19 12:28 5995
drwxr-xr-x 2 www-data www-data 48 Nov 19 14:07 6003
drwxr-xr-x 2 www-data www-data 48 Nov 19 14:28 6010
drwxr-xr-x 2 www-data www-data 48 Nov 19 14:36 6016
drwxr-xr-x 2 www-data www-data 48 Nov 19 14:38 6020
drwxr-xr-x 2 www-data www-data 48 Nov 19 15:10 6023
drwxr-xr-x 2 www-data www-data 48 Nov 19 15:11 6024
drwxr-xr-x 2 www-data www-data 48 Nov 19 15:11 6025
drwxr-xr-x 2 www-data www-data 48 Nov 19 15:18 6026
drwxr-xr-x 2 www-data www-data 48 Nov 19 15:26 6028
drwxr-xr-x 2 www-data www-data 48 Nov 19 15:34 6032
drwxr-xr-x 2 www-data www-data 48 Nov 19 15:35 6034
drwxr-xr-x 2 www-data www-data 48 Nov 19 15:35 6036
msc@bigcentral:~$ ls -ltr /data/GarageTor1024/2019-11-19/
total 12
drwxr-xr-x 2 www-data www-data   74 Nov 19 12:11 5986
drwxr-xr-x 2 www-data www-data   48 Nov 19 12:27 5994
drwxr-xr-x 2 www-data www-data   48 Nov 19 14:06 6001
drwxr-xr-x 2 www-data www-data   74 Nov 19 14:22 6005
drwxr-xr-x 2 www-data www-data   74 Nov 19 14:22 6004
drwxr-xr-x 2 www-data www-data   74 Nov 19 14:22 6002
drwxr-xr-x 2 www-data www-data   48 Nov 19 15:34 6033
drwxr-xr-x 2 www-data www-data   48 Nov 19 18:59 6060
drwxr-xr-x 2 www-data www-data   48 Nov 19 19:15 6062
drwxr-xr-x 2 www-data www-data   48 Nov 19 19:16 6064
drwxr-xr-x 2 www-data www-data   48 Nov 19 19:17 6067
drwxr-xr-x 2 www-data www-data 4096 Nov 19 20:55 6072
drwxr-xr-x 2 www-data www-data   76 Nov 19 20:55 6070
drwxr-xr-x 2 www-data www-data 4096 Nov 19 20:55 6068
drwxr-xr-x 2 www-data www-data   76 Nov 19 20:56 6061
drwxr-xr-x 2 www-data www-data 4096 Nov 19 20:56 6057
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6021
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6017
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6015
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6018
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6019
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6014
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6013
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6012
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6009
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6008
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6011
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6006
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:00 6007
drwxr-xr-x 2 www-data www-data   74 Nov 20 07:01 6000

$ ls -ltr /data/
lrwxrwxrwx 1 www-data www-data   1 Okt 29  2018 Garage -> 2
lrwxrwxrwx 1 www-data www-data   1 Nov  3 17:10 GarageTor1024 -> 6

**To Reproduce**
unknown. the time on the server does not "jumping". NTP works fine and I can see in the syslog that the systime ist "stable".
Not sure if any php? security update caused this issue.
It seems this happens RANDOMLY.
I am using Zoneminder on this server for more then a year without any changes except of security updates

**Expected behavior**
like normal....

**Debug Logs**
```

2019-11-20 12:43:55	web_php		1620	FAT	Can't create frame images from video because there is no video file for this event at (/data/2/2019-11-19/6033/6033-video.mp4	/usr/share/zoneminder/www/views/image.php	167
2019-11-20 12:43:55	web_php		4481	FAT	Can't create frame images from video because there is no video file for this event at (/data/6/2019-11-19/6032/6032-video.mp4	/usr/share/zoneminder/www/views/image.php	167

```

**Comment by connortechnology** [comment] 2019-11-21 18:26
First off, you should update to our latest version 1.33.14. 
sudo add-apt-repository ppa:iconnor/zoneminder-master
sudo apt-get update
sudo apt-get install zoneminder

Second, I think you are seeing problems caused by zmaudit getting confused (which we fixed in 1.33.14). Also you do not need to be running zmaudit, so turn it off.

Lastly, the logs we need to figure it out are debug logs for zmc and zma.

**Closed** 2019-12-03 08:15 UTC
