### ISSUE TITLE
ZM Maxes out a single CPU thread if Network Cam is not avaliable

### ISSUE THREAD

**Issue by Dinsmoor** [ZoneMinder/zoneminder#2174] opened 2018-08-05 03:12 UTC
**ZoneMinder Version (`zmaudit.pl -v`):**
1.30.4

**Linux Distribution and Version (`cat /etc/os-release` or `cat /etc/redhat-release`):**
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

**If the issue concerns a camera, provide the make, model, frame rate, resolution and ZoneMinder Source Type:**
https://wiki.zoneminder.com/SV3C

FFmpeg, but the WIKI entry has all the default info.
Using 720p at 5Hz frame rate, but this really doesn't matter.

The issue is that when a network camera is turned off (such as power, camera, or connection failure) the "blue test video" will go to the highest possible frame rate on a single thread, which for me is about 1200FPS. This hogs an entire core's resources. I was able to get around this by setting a Maximum FPS in the source settings slightly higher than the remote camera's frame rate, this removed the issue, but I don't think this is desired behavior since who is going to have a camera running at 300+FPS.

It's not really a huge issue for most people, since my use case is remote bridged networks that come and go, but it did confuse me for about an hour. For me, it dragged my system to a crawl.

If this is the desired behavior, please close this issue.

My preferred resolution is when the 'test video' is displaying instead of from the source, the fps is automatically limited to a low number until the source video returns. 2fps sounds OK, but anything below 30 is reasonable.

**Comment by knight-of-ni** [comment] 2018-08-05 12:41
This is a duplicate of #1992 which was closed accidentally. It has been reopened.

**Closed by knight-of-ni** 2018-08-05 12:41 UTC
Labels: duplicate
