### ISSUE TITLE
ONVIF authentication for profiles command not working with Trendnet IP862-IC

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/ZoneMinder#1588] opened 2016-08-10 14:03 UTC
Probe finds the camera, but the profiles command gives an auth error.

**Comment by connortechnology** [comment] 2016-08-10 14:09
@altaroca 

/usr/bin/zmonvif-probe.pl -v profiles http://192.168.9.247/onvif/device_service 1.1 admin password
<Fault xmlns="http://schemas.xmlsoap.org/soap/envelope/"><faultcode>SOAP-ENV:Server</faultcode><faultstring>Error deserializing message: Bad top node html at /usr/share/perl5/ONVIF/Deserializer/MessageParser.pm line 89.
 at line 1 at /usr/share/perl5/SOAP/WSDL/Expat/Base.pm line 82.
. 
Message was: 
&lt;html&gt;
&lt;body&gt;
&lt;h1&gt;Unauthorized&lt;/h1&gt;
Please enter correct account/password.
&lt;/body&gt;
&lt;/html&gt;
</faultstring><faultactor>urn:localhost</faultactor></Fault>

**Comment by knnniggett** [comment] 2016-08-10 14:30
We need to poke @altaroca to get his attention.

**Comment by connortechnology** [comment] 2016-08-10 14:51
I did.

**Comment by altaroca** [comment] 2016-08-10 16:50
The obvious first question is: Are you sure you are using the correct credentials?
Some thoughts: 
- the camera might have different sets of credentials for web ui and for onvif.
- the camera might need a password change on the very first login.
- can you authenticate with the same credentials using some other onvif tool?

**Comment by connortechnology** [comment] 2016-08-10 17:36
So far I havn't found a tool that will speak to any of my cameras.  

The lingodigit onvif tool detects my DCS-2310L at least.  

Yes I am sure about the password.  I have also tried the device's default password.

**Comment by knnniggett** [comment] 2016-08-10 17:54
Try using onvif device manager. It should work with that tool if the camera is truly onvif compliant.
https://sourceforge.net/projects/onvifdm/

If it doesn't work with onvif device manager then the camera may not be onvif compliant, despite any marketing claims to the contrary.

**Comment by connortechnology** [comment] 2016-08-10 17:56
onvifdm just hangs in my vm.

**Comment by knnniggett** [comment] 2016-08-10 18:01
Make sure the real network card you bind your vm to has promiscuous mode enabled under the vm settings.

**Comment by connortechnology** [comment] 2016-08-10 21:42
Ok, so odm sees both cameras, and the auth works with the dcs-2310L. Everything works with it.

Auth does not work for the TV-IP862-IC under odm, using either the set credentials or the devices defaults. (Defaults are supposed to be admin/admin.).

**Comment by SteveGilvarry** [comment] 2016-08-10 21:44
http://www.onvif.org/ConformantProducts/ProfileProducts.aspx
Not very much listed here under Trendnet and to claim conformance they should be.

**Comment by knnniggett** [comment] 2016-08-10 23:37
The Onvif standard allows one to browse for cameras on the local network, with no authentication, but everything following that requires it. That of course explains why the first step of the onvif discovery probe worked.  When one digs into how one authenticates via onvif, one encounters a time element which is needed to create the nonce. So if the clock in the camera is not set or is not close to the time on the machine you are on, then, by design, the authentication will not work.  e.g. check the camera clock

**Comment by knnniggett** [comment] 2016-10-04 21:44
@connortechnology Did you make any onvif changes today that might address this?

**Comment by connortechnology** [comment] 2016-10-05 00:30
No.   This camera responds intermittently and has auth problems.   Nowhere does it say that it is onvif compliant... so... this is one of those odd cameras that we may never support.

**Comment by knnniggett** [comment] 2017-05-18 12:36
Closing all the Onvif issues out since the latest release contains improvements to the Onvif probe. Please create a new issue if problems persist.

**Closed by knnniggett** 2017-05-18 12:36 UTC
Labels: ONVIF
