### ISSUE TITLE
Logging should be scrubbed of passwords

### ISSUE THREAD

**Issue by ghulands** [ZoneMinder/ZoneMinder#1799] opened 2017-03-04 18:28 UTC
When zoneminder has an issue opening the stream, it logs something like this

Feb 28 15:24:34 zoneminder zmc_m2[1401]: ERR [Unable to open input rtsp://user:secret@cam01/cam/realmonitor?channel=1&subtype=0 due to: Operation now in pro

It would be good if you scrub the logs of usernames and passwords

**Comment by knnniggett** [comment] 2017-05-18 13:26
duplicate of #767

**Closed by knnniggett** 2017-05-18 13:26 UTC
Labels: duplicate
