### ISSUE TITLE
Timestamp is not shown in the video picture

### ISSUE THREAD

**Issue by schnudd31do3** [ZoneMinder/zoneminder#3968] opened 2024-04-17 13:52 UTC
- Zoneminder 1.37.59
- Installed via deb package (zoneminder_1.37.59~20240417.30-bookworm_amd64.deb)
- Debian bookworm 12.5
- Edge, Chrome, Firefox

- Camera Axis M3005

The time stamp configured here:
![image](https://github.com/ZoneMinder/zoneminder/assets/72391822/7d2bd22e-9f9c-451b-b797-c7e7052716b0)

is not shown in the video picture. 
![image](https://github.com/ZoneMinder/zoneminder/assets/72391822/ea408da6-b2fd-49b8-a75b-3122e225958d)

In the official debian version 1.36.33, it is functioning:
![image](https://github.com/ZoneMinder/zoneminder/assets/72391822/fbde6487-7bd1-4923-9a3f-1542b650ed7a)

**Comment by ovargasp** [comment] 2024-04-21 17:15
schnudd31do3, thanx for the report, I was able to reproduce the behavior, there is in fact a problem reported in the logs about that, it states that a font is missing... that's why you're not seeing the time stamp.

![image](https://github.com/ZoneMinder/zoneminder/assets/59069596/6ef55ee7-75c0-45b2-bfbb-103c45db6d4a)

A new release will fix the problem, but meanwhile there is a work around you can apply: download the file and place it in the corresponding forder. 

The file is located here: https://github.com/ZoneMinder/zoneminder/blob/master/fonts/default.zmfnt

Download it, move it to the corresponding folder and restart zoneminder service so it gets recognized, that'll fix it.

**Comment by connortechnology** [comment] 2024-04-21 19:30
Why was it missing I wonder?  Should have been installed automatically.

**Comment by schnudd31do3** [comment] 2024-04-22 04:44
I tried it twice. I restored my server to the state before updating and it was always the same result.
I will test the work around from https://github.com/ZoneMinder/zoneminder/blob/master/fonts/default.zmfnt

**Comment by schnudd31do3** [comment] 2024-04-22 05:42
There is one question left. Why does the camera image only appear with a delay of about a minute after the URL is opened in the browser? https://mycamserver.de/zm/cgi-bin/zms?mode=jpeg&monitor=1&user=MyUser&pass=MyPass

**Comment by ovargasp** [comment] 2024-04-22 12:36
schnudd31do3, I'm glad you got your first issue fixed, about this second question, to try and figure out the problem is necessary to have some more information, logging, what browsers have you tried, etc. 

I tried to replicate what you're saying but it's working fine in my Debian installs...

**Comment by ovargasp** [comment] 2024-04-22 13:43
Can you open the monitor view and right click on top of  the stream then select "copy the image URL", that will give you a slightly different URL that the one you're using, try and use that one in another browser tab... it's important to leave UI monitor view prior to try and open this URL, because it will use the same randomizer number that the monitor view and it will delay the playback.

**Comment by connortechnology** [comment] 2024-04-22 14:34
I think we would need to turn on debug logging and check the zms_m1.log

**Comment by schnudd31do3** [comment] 2024-04-23 04:33
Thanks. I got you. In my case it is : https://mycamserver.de/zm/cgi-bin/nph-zms?mode=jpeg&maxfps=&scale=100&state=1&monitor=1&auth=1315899ba107d0c2d0625ae643be8b5e&user=admin&rand=1713846240&connkey=308082. Opened in a separate tab does not show the video picture.

**Comment by schnudd31do3** [comment] 2024-04-23 06:35
No errors, only waiting for responding.
![image](https://github.com/ZoneMinder/zoneminder/assets/72391822/d848a812-e652-41ff-b21e-770f520011f0)

**Comment by schnudd31do3** [comment] 2024-04-23 07:50
I observed, restarting the zoneminder service causes about 4 seconds of delay while the website is kep open. Restarting the apache2 service causes a delay of about 36 seconds, where I have to refresh the website immediately after restarting the apache2 service.

**Comment by ovargasp** [comment] 2024-04-24 17:37
Have you tried to access the monitor using the browser in "safe mode", that may give you an idea if is related to some browser extesion... another thing you can check is if the CPU usage spikes when you open the monitor view, that can cause a delay.

**Comment by schnudd31do3** [comment] 2024-04-25 05:24
1. I dont know how to activate "safe mode". I am not running it in a docker container.
2. When opening with "mode=single", the picture ist shown immediately and by presing F5 as fast as I want, the video image ist updated without any delay. But using "mode=jpeg", the delay is there. Because cgi-bin/zms is a compiled file, I am not able to dig in, what the delay causes. I guess, that zms is buffering some frames before it shows the video image. An indication for that is that when stopping the zoneminder service, the video image continues for a few seconds.
3. I am using 4 core with 2 CPU per socket and 4GB RAM. vSphere shows no spike when opening the URL and is running on about 15% of CPU load. So I dont beleve that there is a lack of power.

Can you confirm 2. from above? If so, where can I disable this behaviour? I know for a fact that this behavior wasn't the case until some previous versions and I did not change my hardware

**Comment by connortechnology** [comment] 2024-04-25 14:42
The answers will be in the zms logs. The CSP stuff is caused by some chrome extension. I don't think it is related.  However you may try turning off extensions one by one until that goes away.

A bigger issue is a misconfig on your logging path.. it can't write to /var/log/zoneminder.log.  This is a strange value.  Logs should be in /var/log/zm/ so something is strange with your config.  Please check /etc/zm/conf.d/01-system-paths.conf

**Comment by connortechnology** [comment] 2024-04-25 14:44
zms does not buffer frames.  It waits for zmc to have captured another image, then sounds that out.  There is a weird thing with Chrome where it doesn't display an image until it gets a second one.  For this reason we actually sometimes send the same image twice.  However I don't think this is relevant.

**Comment by schnudd31do3** [comment] 2024-04-30 06:52
I checked this 01-system-paths.conf. I had the path configured here: ZM_PATH_LOGS=/var/log/zm. Perhaps it was an old error.

You said "It waits for zmc to have captured another image". But why can I capture immediately images as fast as I want by using the single mode and pressing F5? Where can check, on what zns is waiting for when using the jped mode?

**Comment by connortechnology** [comment] 2024-04-30 20:02
I just saw this problem today on a support call.  Despite my best efforts to figure it out, so far I am stumped.  They had two identical servers and one did it while the other did not.  Independent of browser.  zms logs clearly show images being sent, but the browser refuses to display them for around a minute.  Also seems to not receive sigpipe when we browse away.  Very puzzling.  Logs all green.

**Comment by schnudd31do3** [comment] 2024-04-30 20:42
Thanks, that you could confirm my observations. "ogs all green." yes they are. I am pretty sure that in former versions of zms, it does not have this issue. But I could not remember since when it comes up.

**Comment by SteveGilvarry** [comment] 2024-09-13 03:35
Closing out as original issue with missing font was resolved. Please create a new issue to track browser delays secondary issue you experienced or if @connortechnology wants one created to track that issue

**Closed by SteveGilvarry** 2024-09-13 03:35 UTC

**Comment by connortechnology** [comment] 2024-09-13 13:15
Just wanted to add an update RE my support call.  That issue was resolved after discovering that the second server didn't have as many cpu cores.  (Dual socket, only 1 socket filled).  Adding another cpu solved that problem.

Doesn't really explain much though.  mode=single uses a different code path and just sends out whatever the last image was and exits. mode=jpeg sends the last image and then waits for the next.  Also, there is the communication socket setup so that we can send STOP/PAUSE get fps rates etc.
