### ISSUE TITLE
zmonvif-probe.pl issues if server has multiple network interfaces

### ISSUE THREAD

**Issue by ziotibia81** [ZoneMinder/ZoneMinder#2031] opened 2018-01-09 09:49 UTC
Case 1):
if server has one or more network interface but doesn't have a default gateway zmonvif.probe.pl crash:

```
root@argo:~# zmonvif-probe.pl -vvv probe
Probing for SOAP 1.1
Cannot open multicast socket to 239.255.255.250:3702 at /usr/share/perl5/WSDiscovery/TransportUDP.pm line 67.
``` 

Case 2):
if server has multiple network interfaces zmonvif.probe.pl probe only the interface with default gateway.

In my case there are one interface only for network cams, and another interface, with default gateway, for zm web ui. 

**ZoneMinder Version (`zmaudit.pl -v`):** 1.30.4

**Linux Distribution and Version (`cat /etc/os-release` or `cat /etc/redhat-release`):**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

**Comment by knnniggett** [comment] 2018-01-09 13:08
Duplicate of #1653 

Would love to have someone with the spare time to take take a look at this.

**Closed by knnniggett** 2018-01-09 13:08 UTC
